# Use an official Node.js runtime as a parent image

FROM node:16

# Set the working directory in the container to /app

WORKDIR /usr/src/app

# Copy package.json file into the container

COPY package*.json ./

# Install any needed packages specified in package.json

RUN npm install

# Install nodemon globally

RUN npm install -g nodemon

# Copy the rest of the application code into the container

COPY . .

# Make port 5000 available to the world outside this container

EXPOSE 5000

# Command to run the application

CMD ["nodemon", "server.js"]

